### ISSUE TITLE
Key bindings not registered

### ISSUE THREAD

**Issue by pvencill** [evandrocoan/PlantUmlDiagrams#7]
Installed through Package Manager, I have a PlantUML server running at localhost:8080 and updated the User Settings to point to that server, but key combo CMD+ALT+M minimizes the ST3 window, as does CMD+M.  ALT+M does nothing.  Tried all three while having one of the Example diagrams highlighted, with the described results.  There is no menu option I could find to manually ask ST3 to render a diagram either, w/o the key combo.  

After manually adding the key combo to the User key binding file like so:

```JSON
[
    {"keys": ["alt+m"], "command": "display_diagrams"}
]
```

Highlighting the diagram text and using the ald+m key combo I get a new tab opened with a "Loading image..." text that never changes.

**Comment by evandrocoan** [comment]
Hi,

Can you copy the contents of your Sublime Text console when you see the `"Loading image..." text that never changes`?

You can open your Sublime Text console by going on the menu `View -> Show Console`.

**Comment by pvencill** [comment]
So it was two errors, and I figured it out. 

For posterity, the issue was first that I was running the local PlantUML server, but the SublimeText plugin could not connect to it because I was running the docker-based server, which serves PlantUML at http://localhost:8080/ rather than what the plugin expects: http://localhost:8080/plantuml.  Changing the setting in my User Settings file didn't fix that, it kept looking for the Jar, which of course was not present because I thought I was hitting the local server.  

Downloading the Jar, updating my User Settings to look in the right spot for the Jar and restarting ST3 fixed the issue for me.
