### ISSUE TITLE
can't install via packagecontroll

### ISSUE THREAD

**Issue by videni** [evandrocoan/PlantUmlDiagrams#8]
# Error
```
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'portalockerfile' is not currently installed; installing...
Package Control: The dependency 'portalockerfile' is not available
Package Control: The dependency 'portalockerfile' could not be installed or updated
```

# Step

 install this package via package control

# Enviroment

sublime text 3197 on mac

# Edit

I switch to install this package with `git clone`, I can  see this package is successfully installed, but the `display diagram`  command  can be found.
![image](https://user-images.githubusercontent.com/4058341/55383554-12f5e300-555b-11e9-9158-2d3282fb9671.png)

![image](https://user-images.githubusercontent.com/4058341/55383532-07a2b780-555b-11e9-8aa6-9c8a8bf0d550.png)

I have added all congurations
 key binding 
```
  { "keys":  ["alt+m"], "command": "display_diagrams"}
```

package settings
```
{
"plantuml_server": "http://www.plantuml.com/plantuml/",
    "jar_file": "/usr/local/bin/plantuml.jar",
}
```
nothing works

**Comment by evandrocoan** [comment]
Last year I renamed my external dependency. This is pending to be renamed here:
1. https://github.com/wbond/package_control_channel/pull/7389 Fixed my dependencies URLs names not on lowercase convention

For now you can don this:
1. Go to the menu `Preferences -> Package Control`
1. Type `Add Channel` on the opened quick panel and press enter
1. Then enter the following address and press enter:
   ```
   https://raw.githubusercontent.com/evandrocoan/SublimeStudioChannel/master/channel.json
   ```
1. Then, try to install the package again.

**Comment by videni** [comment]
@evandrocoan, thank you , it works.
